SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count FROM UK_CARDS_ANALYTICS.RAW.CUSTOMERS
UNION ALL
SELECT 'ACCOUNTS', COUNT(*) FROM UK_CARDS_ANALYTICS.RAW.ACCOUNTS
UNION ALL
SELECT 'TRANSACTIONS', COUNT(*) FROM UK_CARDS_ANALYTICS.RAW.TRANSACTIONS
UNION ALL
SELECT 'REPAYMENTS', COUNT(*) FROM UK_CARDS_ANALYTICS.RAW.REPAYMENTS
UNION ALL
SELECT 'CREDIT_DECISIONS', COUNT(*) FROM UK_CARDS_ANALYTICS.RAW.CREDIT_DECISIONS;